name: Automated API tests using Postman CLI

on: 
    workflow_dispatch:
    push:
jobs:
  automated-api-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          powershell.exe -NoProfile -InputFormat None -ExecutionPolicy AllSigned -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))"
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "11237029-2f8a03bb-cfa5-4747-9b8f-d8a4ba4aeb19" -e "11237029-b57b9734-985b-430f-b792-c68cbd3a3ec7"
          -name: logout
           run: postman logout --with-api-key ${{ secrets.POSTMAN_API_KEY }}
